language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/topups

node_js:
  - 12
before_script:
  - psql -c 'create database topups;' -U postgres
  - psql -U postgres -d topups -a -f db.sql
services:
  - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4